#!/bin/bash

ROOT=`dirname $0`

function compiler() {
	$ROOT/qml-compiler $@
}

#fix --compilation_level ADVANCED_OPTIMIZATIONS
function minify() {
	java -jar compiler/gcc/compiler.jar --warning_level VERBOSE --externs compiler/gcc/jquery-1.9.js app/qml.js > app/qml.min.js || die "gcc failed"
}

function package() {
	platform=$1
	pkg=`mktemp -d -p .`
	cp -ra app/* $pkg
	rm $pkg/app.html $pkg/qml.js
	cp $ROOT/platform/$platform/dist/* $pkg
	suffix=`date '+%Y%m%d-%H%M%S'`
	pushd $pkg >/dev/null
	zip -r0 ../${platform}-${suffix}.zip *
	popd >/dev/null
	rm -rf $pkg
}

if [ $# -eq 0 ]; then
	echo "usage: [compile|minify|package] *args"
	exit
fi

case $1 in
	compile)
		compiler ${@:2}
	;;
	package)
		package ${@:2}
	;;
	minify)
		minify ${@:2}
	;;
	*)
		echo "invalid command line $@"
		exit 1
	;;
esac
